### PR TITLE
add integration test for cli

### PR DESCRIPTION
**Pull request by calcsam**
@smthomas @abettke -- curious for thoughts on the right approach here.  

Would you be able to (1) make sure these run for you locally (2) share thoughts / feedback on the approach? 

I took this approach because it felt cleaner than trying to mock everything. And it _does_ work. But...feels like a decent bit of setup.

Any suggestions to make this cleaner or simpler would be appreciated. I'll clean up the logging before we merge.

### CODE REVIEW

**Review by abettke — COMMENTED** [review]
It makes sense to want to test this in the fashion that developers will actually use the tool (by invoking commands against the CLI). Although I think it might be more fitting to test the top level commands as functions and then create a very small test suite that ensures our integration with command is in place.

1.) Test calling the functions directly and assert they produce the proper artifacts.
2.) Test exec'ing the commands and spy on the underlying functions to make sure they are called with the proper arguments

**Review by smthomas — APPROVED** [review]
I think this really qualifies as more of an E2E test for a CLI. Overall, I think it's useful to actually run through on the simple happy path example.

There are probably ways we can add some integration/unit tests where we test the inputs/outputs of some functions. That said, E2E testing in this way would likely catch a lot of bugs with the overall workflow.

If it works, I say we ship it and add some unit tests later.

**Comment by calcsam** [comment]
@abettke can you try again now?

**Comment by calcsam** [comment]
I'm gonna go ahead and merge this to reduce WIP. It's for local dev only right now, since it requires docker.

**Pull request merged**
